"""Initial migration.

Revision ID: a9b95d91418d
Revises: 
Create Date: 2022-05-29 17:29:20.606038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b95d91418d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('prix', sa.Float(), nullable=True),
    sa.Column('fournisseur', sa.String(length=200), nullable=True),
    sa.Column('info', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=True),
    sa.Column('categorie', sa.String(length=200), nullable=True),
    sa.Column('descriptif', sa.Text(), nullable=True),
    sa.Column('periodicite', sa.Integer(), nullable=True),
    sa.Column('unite', sa.String(), nullable=True),
    sa.Column('cout', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('prix', sa.Float(), nullable=True),
    sa.Column('fournisseur', sa.String(length=200), nullable=True),
    sa.Column('info', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=True),
    sa.Column('ville', sa.String(length=200), nullable=True),
    sa.Column('info', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sousensemble',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=True),
    sa.Column('info', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materieltype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marque', sa.String(length=200), nullable=True),
    sa.Column('modele', sa.String(length=200), nullable=True),
    sa.Column('categorie', sa.String(length=200), nullable=True),
    sa.Column('info', sa.String(length=200), nullable=True),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('metier', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'user_id')
    )
    op.create_table('document_materieltype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=250), nullable=True),
    sa.Column('descriptif', sa.String(length=250), nullable=True),
    sa.Column('materieltype_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['materieltype_id'], ['materieltype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gammes',
    sa.Column('gamme_id', sa.Integer(), nullable=False),
    sa.Column('materieltype_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gamme_id'], ['gamme.id'], ),
    sa.ForeignKeyConstraint(['materieltype_id'], ['materieltype.id'], ),
    sa.PrimaryKeyConstraint('gamme_id', 'materieltype_id')
    )
    op.create_table('listeoutils',
    sa.Column('outils_id', sa.Integer(), nullable=False),
    sa.Column('materieltype_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['materieltype_id'], ['materieltype.id'], ),
    sa.ForeignKeyConstraint(['outils_id'], ['outils.id'], ),
    sa.PrimaryKeyConstraint('outils_id', 'materieltype_id')
    )
    op.create_table('materiel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(length=200), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('materieltype_id', sa.Integer(), nullable=False),
    sa.Column('info', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['materieltype_id'], ['materieltype.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sousensembles',
    sa.Column('sousensemble_id', sa.Integer(), nullable=False),
    sa.Column('materieltype_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['materieltype_id'], ['materieltype.id'], ),
    sa.ForeignKeyConstraint(['sousensemble_id'], ['sousensemble.id'], ),
    sa.PrimaryKeyConstraint('sousensemble_id', 'materieltype_id')
    )
    op.create_table('ordre_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origine_om', sa.String(length=30), nullable=True),
    sa.Column('materiel_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=True),
    sa.Column('date_cloture', sa.DateTime(), nullable=True),
    sa.Column('om_status', sa.String(length=30), nullable=False),
    sa.Column('objet', sa.Text(), nullable=True),
    sa.Column('cause', sa.String(length=30), nullable=True),
    sa.Column('amelioration', sa.Text(), nullable=True),
    sa.Column('gamme_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gamme_id'], ['gamme.id'], ),
    sa.ForeignKeyConstraint(['materiel_id'], ['materiel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_om',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=250), nullable=True),
    sa.Column('descriptif', sa.String(length=250), nullable=True),
    sa.Column('om_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['om_id'], ['ordre_maintenance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intervention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('om_id', sa.Integer(), nullable=False),
    sa.Column('date_intervention', sa.DateTime(), nullable=True),
    sa.Column('heure_debut', sa.DateTime(), nullable=True),
    sa.Column('heure_fin', sa.DateTime(), nullable=True),
    sa.Column('operateur_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['om_id'], ['ordre_maintenance.id'], ),
    sa.ForeignKeyConstraint(['operateur_id'], ['operateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_inter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=250), nullable=True),
    sa.Column('descriptif', sa.String(length=250), nullable=True),
    sa.Column('intervention_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['intervention_id'], ['intervention.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interventions',
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('materiel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['intervention.id'], ),
    sa.ForeignKeyConstraint(['materiel_id'], ['materiel.id'], ),
    sa.PrimaryKeyConstraint('intervention_id', 'materiel_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interventions')
    op.drop_table('document_inter')
    op.drop_table('intervention')
    op.drop_table('document_om')
    op.drop_table('ordre_maintenance')
    op.drop_table('sousensembles')
    op.drop_table('materiel')
    op.drop_table('listeoutils')
    op.drop_table('gammes')
    op.drop_table('document_materieltype')
    op.drop_table('roles')
    op.drop_table('operateur')
    op.drop_table('materieltype')
    op.drop_table('user')
    op.drop_table('sousensemble')
    op.drop_table('site')
    op.drop_table('role')
    op.drop_table('outils')
    op.drop_table('gamme')
    op.drop_table('article')
    # ### end Alembic commands ###
